version: '3.8'

services:
  app:
    container_name: odyssi-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${DB_USER:-odyssi}:${DB_PASSWORD:-odyssi_password}@postgres:5432/${DB_NAME:-odyssi_db}
      AUTH_TRUST_HOST: "true"
      AUTH_SECRET: ${AUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@odyssi.com}
    command: >
      sh -c "npx prisma migrate deploy && node server.js"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./backups:/app/backups
    depends_on:
      - postgres
    networks:
      - odyssi-network

  postgres:
    container_name: odyssi-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-odyssi}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-odyssi_password}
      POSTGRES_DB: ${DB_NAME:-odyssi_db}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5434}:5432"
    networks:
      - odyssi-network

volumes:
  postgres_data:


networks:
  odyssi-network:
    driver: bridge
