version: '3.8'

services:
  app:
    container_name: odyssi-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5024:3000"
    environment:
      DATABASE_URL: postgresql://odyssi:odyssi_password@postgres:5432/odyssi_db
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_SECRET: NB7UOWeYYaYdVYcOrDPfBUaQu66xkaQFRMra2oIk
      NEXTAUTH_URL: https://odys.si
      ADMIN_EMAIL: admin@odyssi.com,p@rk.ci
    command: >
      sh -c "npx prisma migrate deploy && node server.js"
    volumes:
      - /volume1/docker/odyssi/public/uploads:/app/public/uploads
      - /volume1/docker/odyssi/backups:/app/backups
    depends_on:
      - postgres
    networks:
      - odyssi-network

  postgres:
    container_name: odyssi-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: odyssi
      POSTGRES_PASSWORD: odyssi_password
      POSTGRES_DB: odyssi_db
    volumes:
      - /volume1/docker/odyssi/postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - odyssi-network

volumes:
  postgres_data:


networks:
  odyssi-network:
    driver: bridge
